### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by krostkowski** [abalmus/aurelia-ace-editor#2]
When installing:

> jspm install github:abalmus/aurelia-ace-editor
>      Looking up github:abalmus/aurelia-ace-editor
>      Updating registry cache...
>      Downloading github:abalmus/aurelia-ace-editor@master
>      warn Error on processPackageConfig
>      Package.json dependency ace set to github:ajaxorg/ace-builds@^1.2.3, which is not a va
> lid dependency format for npm.
>      It's advisable to publish jspm-style packages to GitHub or another registry so convent
> ions are clear.
> warn Error processing package config for github:abalmus/aurelia-ace-editor.
> err  Error processing package config for github:abalmus/aurelia-ace-editor.
> warn Installation changes not saved.

I'm using jspm 0.16.34

**Comment by mrpetz** [comment]
Hi @krostkowski, let me check your jspm version. Seems like 0.15 worked well for me.

**Comment by abalmus** [comment]
Hi @krostkowski I've set **"jspmNodeConversion": false** it should fix the problem, try install it one more time and let me know.

**Comment by krostkowski** [comment]
Now it works. Thanks.
