### ISSUE TITLE
Error initializing theme and mode

### ISSUE THREAD

**Issue by giacomodeliberali** [abalmus/aurelia-ace-editor#3]
After registring it as a plugin in main.ts, I can't figure out how to use this component.
When i try to change mode/theme it search for it in wrong folder (http://localhost:8080/src/ace/theme-monokai.js,  http://localhost:8080/src/ace/mode-javascript.js). How can i solve that?

Furthermore, the plugin doesnt render in safari browser. How can i fix that? Thanx in advance

**Comment by abalmus** [comment]
Hi @deliberaligiacomo,
Could you post your jspm config ?

**Comment by giacomodeliberali** [comment]
`map: {
    ...,
    "abalmus/aurelia-ace-editor": "github:abalmus/aurelia-ace-editor@master",
    "github:abalmus/aurelia-ace-editor@master": {
      "ace": "github:ajaxorg/ace-builds@1.2.3"
    },
    ...
}`

**Comment by abalmus** [comment]
@deliberaligiacomo,
It looks good, I didn't try it with TS project, maybe this is the problem. Let me check it and get back to you.

**Comment by deliberaligiacomo** [comment]
Ok i'll wait, thanx

**Comment by abalmus** [comment]
Hi @deliberaligiacomo,
I've just checked it with fresh TS skeleton app, it works pretty well even in safari.

please make sure you included styles into your project.

`

<style>
    .ace_editor {
        display: block;
        border: 1px solid lightgray;
        margin: auto;
        height: 300px;
        width: 100%;
    }
  </style>

`

**Comment by giacomodeliberali** [comment]
Can you give me a working piece of code? Because from the examples that i've seen I don't know where I'm wrong.
1. main.ts: `aurelia.use.plugin('abalmus/aurelia-ace-editor');`
2. ace-test.html:
-  `<style>
      .ace_editor {
          display: block;
          border: 1px solid lightgray;
          margin: auto;
          height: 300px;
          width: 100%;
      }
  </style>`
- `<ace config-theme="ace/theme/monokai" config-mode="ace/mode/javascript" class="ace_editor"> console.log("content"); </ace>`

Furthermore when i start typing, the content doesn't change, and the console signlas me an error (the last red line).
![ace](https://cloud.githubusercontent.com/assets/4717227/16759346/afda094e-4816-11e6-81fa-22c49089f0aa.PNG)

**Comment by abalmus** [comment]
Yes sure. 
1. Download the skeleton
2. npm install
3. jspm install
4. jspm install github:abalmus/aurelia-ace-editor
5. insert following line in main.ts `aurelia.use.plugin('abalmus/aurelia-ace-editor');` 

And here is how I inserting editor component:

`````` <template>
 <style>
    .ace_editor {
        display: block;
        border: 1px solid lightgray;
        margin: auto;
        height: 300px;
        width: 100%;
    }
  </style>
    <ace config-theme="ace/theme/eclipse"
         config-mode="ace/mode/json">
        {
            "menu": {
                "id": "file",
                "value": "File",
                "popup": {
                    "menuitem": [
                        {"value": "New", "onclick": "CreateNewDoc()"},
                        {"value": "Open", "onclick": "OpenDoc()"},
                        {"value": "Close", "onclick": "CloseDoc()"}
                    ]
                }
            }
        }
    </ace>
</template>```
``````

**Comment by giacomodeliberali** [comment]
That's seems equal to mine. Can't figure out what the problem is

**Comment by abalmus** [comment]
I compressed my app, please run `npm install && jspm install -y`
[skeleton-typescript.zip](https://github.com/abalmus/aurelia-ace-editor/files/358852/skeleton-typescript.zip)

**Comment by abalmus** [comment]
after that I'm running `gulp watch`

**Comment by giacomodeliberali** [comment]
It always giving me the same errors of above. Even your skeleton project. Ideas?
![ace1](https://cloud.githubusercontent.com/assets/4717227/16764863/1b1b3af6-4831-11e6-931c-efc09ce277b3.PNG)

**Comment by abalmus** [comment]
Yes after clear cache, I'm getting this errors in the console. Loos like some changes in new version of System.JS. I'll take a look today, it is something with System normalize url.

**Comment by abalmus** [comment]
Hi @deliberaligiacomo,
could you please try to run `jspm install ace` and see if it works after that?

**Comment by giacomodeliberali** [comment]
Seems fixed, I had installed ace-builds with npm. Where did you find that jspm package?

**Comment by abalmus** [comment]
github:ajaxorg/ace-builds

**Comment by giacomodeliberali** [comment]
OK, seems good the plugin, but still can't render in safari browser. Am I missing any tricks?

**Comment by abalmus** [comment]
In Safari 9.0.2 works well for me :(
<img width="1079" alt="screen shot 2016-07-13 at 1 56 05 pm" src="https://cloud.githubusercontent.com/assets/7634278/16801149/b5206b28-4901-11e6-9a77-396d5cc8baa1.png">

**Comment by abalmus** [comment]
Do you see nay errors in Safari ?

**Comment by giacomodeliberali** [comment]
Ok fixed safari issue. 
In my component i used your `<style>` before `<template>`. After moving that class inside global .less it's all fixed. Seems that safari ignores my `<style>` inside the component `<html>`. Thanks for the support, all closed.
