### ISSUE TITLE
Binding content from template is one-way

### ISSUE THREAD

**Issue by jdposthuma** [abalmus/aurelia-ace-editor#4]
I might be missing something, but the following code only binds one-way:

`<ace content.bind="editSetting.dataString" config-theme="ace/theme/chrome" config-mode="ace/mode/json"></ace>`

Great library, BTW!

**Comment by abalmus** [comment]
try `content.two-way="editSetting.dataString"`

**Comment by abalmus** [comment]
Ignore my last comment. I think I understand what you mean, this requires to subscribe on change event and update the content. But this is a good idea to make it two way binding by default, I'll have a look.

As a solution for now get the instance of the ace editor and subscribe on `change` event.

something like:

editor.on("change", function() {
    // update content 
});

more infor: https://ace.c9.io/#nav=api&api=editor

**Comment by jdposthuma** [comment]
Thanks! At this point, my integration doesn't _need_ real-time binding, so I'm just grabbing the content when the user clicks ok:

`this.editor.getSession().getValue()`

**Comment by abalmus** [comment]
Yea, thats good enough. 

Related to two-way binding, I'm also thinking about performance, if it ok to update the model every time you change the content. :(

**Comment by jdposthuma** [comment]
true

_Jason Posthuma_
_Developer_
_303-210-4525_
