### ISSUE TITLE
How to use with the CLI

### ISSUE THREAD

**Issue by AStoker** [abalmus/aurelia-ace-editor#5]
Has there been any success with using this with the Aurelia CLI?  
Getting errors that could be configuration related.
``` javascript
{
            "name":"aurelia-ace-editor",
            "path": "../node_modules/aurelia-ace-editor/dist/amd",
            "main": "ace-editor"
          },
```
This configuration results in it complaining about the dependency `ace`. However, when installing with npm, you don't want to install `ace`, since that's the uncompiled repo, you want `ace-builds` which includes just the built files for Ace.

**Comment by Thanood** [comment]
Could you use a requirejs map (or path, not sure) to map ace-build to ace?

**Comment by AStoker** [comment]
Maybe, but that would tie in module loader specific configuration, which I'm not hoping to do.

**Comment by abalmus** [comment]
HI guys, sorry busy days and holidays :) 
I didn't try installing it with CLI, I'll have a look and try to reproduce the issue.

**Comment by abalmus** [comment]
@AStoker to get it to work, please install ace-builds:
`npm install ajaxorg/ace-builds --save`

and use this config: 
```
{
            "name": "aurelia-ace-editor",
            "path": "../node_modules/aurelia-ace-editor/dist/amd",
            "main": "ace-editor"
          },
          {
            "name": "ace",
            "path": "../node_modules/ace-builds/src",
            "main": "ace"
          }
```
and do not forget to register it ;)
`aurelia.use.globalResources('aurelia-ace-editor');`

**Comment by FedericoGalf** [comment]
I'm using aurelia-cli and after ace-builds installation, I still have those errors when I try to implement the editor:
<img width="487" alt="screen shot 2017-04-13 at 14 38 29" src="https://cloud.githubusercontent.com/assets/16799422/25004907/e5a2cc64-2056-11e7-90df-5e3fe97d706f.png">
<img width="489" alt="screen shot 2017-04-13 at 14 38 11" src="https://cloud.githubusercontent.com/assets/16799422/25004911/e8c525f4-2056-11e7-8380-9debe44a4329.png">

I'm using the static config:
``` 
<ace config-theme="ace/theme/eclipse"
     config-mode="ace/mode/json">
    {
        "menu": {
            "id": "file",
            "value": "File",
            "popup": {
                "menuitem": [
                    {"value": "New", "onclick": "CreateNewDoc()"},
                    {"value": "Open", "onclick": "OpenDoc()"},
                    {"value": "Close", "onclick": "CloseDoc()"}
                ]
            }
        }
    }
</ace>

```

**Comment by gcrscott** [comment]
Do you know if there is possible to use custom themes/modes? I'm getting the same errors in vendor-bundle.

![image](https://user-images.githubusercontent.com/6887671/82622018-561d7600-9ba2-11ea-90f9-5bc046d01b33.png)

These files are outside of node_modules (i.e. src/resources/custom-aurelia-ace-editor/mode-tokens.js)
